; This file was auto-generated by drush_make
core = 6.x

api = 2
projects[drupal][version] = "6.20"

; Profiles
projects[uberdrupal-6-20][type] = "profile"
;projects[uberdrupal-6-20][subdir] = "profiles/uberdrupal"
projects[uberdrupal-6-20][download][type] = "git"
projects[uberdrupal-6-20][download][url] = "git://github.com/benhosmer/Ubderdrupal-6.20.git"

; Modules
projects[acl][version] = "1.3"

projects[addthis][version] = "2.10"

projects[admin][version] = "2.0"

projects[admin_menu][subdir] = "profiles/uberdrupal/modules/admin_menu"
projects[admin_menu][version] = "1.6"

projects[quiz][version] = "4.0"

projects[announcements][version] = "1.0"

projects[autoload][version] = "2.0"

projects[blocks404][version] = "1.3"

projects[ubercart][subdir] = "profiles/uberdrupal/modules/ubercart"
projects[ubercart][version] = "2.4"

projects[cck][version] = "2.9"

projects[content_access][version] = "1.2"

projects[content_profile][version] = "1.0"

projects[devel][version] = "1.23"

projects[features][version] = "1.0"

projects[filefield][version] = "3.9"

projects[fivestar][version] = "1.19"

projects[swftools][version] = "2.5"

projects[imageapi][subdir] = "profiles/uberdrupal/modules/imageapi"
projects[imageapi][version] = "1.9"

projects[imagecache][subdir] = "profiles/uberdrupal/modules/imagecache"
projects[imagecache][version] = "2.0-beta10"

projects[imagefield][version] = "3.9"

projects[lightbox2][subdir] = "profiles/uberdrupal/modules/lightbox2"
projects[lightbox2][version] = "1.11"

projects[module_filter][version] = "1.5"

projects[pathauto][version] = "1.5"

projects[simplenews][version] = "1.3"

projects[skinr][version] = "1.6"

projects[token][version] = "1.15"

projects[uc_node_access][version] = "1.x-dev"

projects[userpoints_ubercart][version] = "2.x-dev"

projects[video][version] = "4.2-alpha2"

projects[userpoints][version] = "1.1"

projects[views][version] = "2.12"

projects[votingapi][version] = "2.3"

; Themes
projects[fusion][subdir] = "profiles/uberdrupal/themes/fusion"
projects[fusion][version] = "1.0"

projects[acquia_prosper][subdir] = "profiles/uberdrupal/themes/acquia_prosper"
projects[acquia_prosper][version] = "1.1"

